/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutUsersIndexRouteImport } from './routes/_layout/users/index'
import { Route as LayoutUsersCreateRouteImport } from './routes/_layout/users/create'
import { Route as LayoutUsersUserIdIndexRouteImport } from './routes/_layout/users/$userId/index'
import { Route as LayoutUsersUserIdEditRouteImport } from './routes/_layout/users/$userId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersIndexRoute = LayoutUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersCreateRoute = LayoutUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersUserIdIndexRoute = LayoutUsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersUserIdEditRoute = LayoutUsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/profile': typeof LayoutProfileRoute
  '/': typeof LayoutIndexRoute
  '/users/create': typeof LayoutUsersCreateRoute
  '/users': typeof LayoutUsersIndexRoute
  '/users/$userId/edit': typeof LayoutUsersUserIdEditRoute
  '/users/$userId': typeof LayoutUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/profile': typeof LayoutProfileRoute
  '/': typeof LayoutIndexRoute
  '/users/create': typeof LayoutUsersCreateRoute
  '/users': typeof LayoutUsersIndexRoute
  '/users/$userId/edit': typeof LayoutUsersUserIdEditRoute
  '/users/$userId': typeof LayoutUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/users/create': typeof LayoutUsersCreateRoute
  '/_layout/users/': typeof LayoutUsersIndexRoute
  '/_layout/users/$userId/edit': typeof LayoutUsersUserIdEditRoute
  '/_layout/users/$userId/': typeof LayoutUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/profile'
    | '/'
    | '/users/create'
    | '/users'
    | '/users/$userId/edit'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/profile'
    | '/'
    | '/users/create'
    | '/users'
    | '/users/$userId/edit'
    | '/users/$userId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/profile'
    | '/_layout/'
    | '/_layout/users/create'
    | '/_layout/users/'
    | '/_layout/users/$userId/edit'
    | '/_layout/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users/': {
      id: '/_layout/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users/create': {
      id: '/_layout/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof LayoutUsersCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users/$userId/': {
      id: '/_layout/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof LayoutUsersUserIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users/$userId/edit': {
      id: '/_layout/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof LayoutUsersUserIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutUsersCreateRoute: typeof LayoutUsersCreateRoute
  LayoutUsersIndexRoute: typeof LayoutUsersIndexRoute
  LayoutUsersUserIdEditRoute: typeof LayoutUsersUserIdEditRoute
  LayoutUsersUserIdIndexRoute: typeof LayoutUsersUserIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutUsersCreateRoute: LayoutUsersCreateRoute,
  LayoutUsersIndexRoute: LayoutUsersIndexRoute,
  LayoutUsersUserIdEditRoute: LayoutUsersUserIdEditRoute,
  LayoutUsersUserIdIndexRoute: LayoutUsersUserIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
